server:
  port: 8080 #项目端口号
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///db_sys_crm
    username: root
    password: 123456 #数据库链接信息配置
logging:
  level:
    com:
      o2ocrm: debug #日志打印

