server:
  port: 2080 #项目端口号
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///db_sys_crm
    username: root
    password: 123456 #数据库连接信息配置
  redis:
    host: 127.0.0.1 #连接redis的主机ip
    port: 6379
    password: 123456
    timeout: 1000 #连接超时时间
    jedis:
      pool:
        max-active: 30 #给定时间内最大的连接数，使用负值表示没有限制
        max-idle: 10 #最大空闲连接数
        min-idle: 1 #最小空闲连接数
        max-wait: -1 #连接池最大等待时间，-1表示没有限制
logging:
  level:
    com:
      o2ocrm: debug #日志打印
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启mybatis的驼峰转换，当手写sql语句时必须启用